name: jupyterbook-env
channels:
  - conda-forge
dependencies:
  - python=3.12.0
  - jupyter-book
  - notebook
  - ipykernel
  - pip
  - numpy
  - pandas
  - kagglehub
  - ucimlrepo
  - matplotlib
  - seaborn
  